## Debug tensor shapes

In [2]:
import tensorflow as tf
import numpy as np

In [55]:
reward_history = [tf.convert_to_tensor([-5.2557855]), tf.convert_to_tensor([-5.623535])]
reward_history = tf.reshape(reward_history, [np.shape(reward_history)[0]])
final_state = tf.convert_to_tensor([[-0.7516037, -0.6596149, -1.6440141]])
reached_done = False
# bootstrapped_value = tf.convert_to_tensor([0.1187661])
final_value = tf.convert_to_tensor([0.1187661])
value_history = tf.convert_to_tensor([0.0196585, 0.06741829, 0.1187661])
deltas = tf.convert_to_tensor([-5.2086997 -5.5733747])
advantages = [tf.convert_to_tensor([-10.450459]), tf.convert_to_tensor([-5.5733747])]
returns = [tf.convert_to_tensor([-10.823086]), tf.convert_to_tensor([-5.623535])]

In [98]:
reward_history = [tf.convert_to_tensor([-10.]), tf.convert_to_tensor([-12.])]
reward_history = tf.reshape(reward_history, [np.shape(reward_history)[0]])
final_state = tf.convert_to_tensor([[-0.11, -0.6, -2.]])
reached_done = False
# bootstrapped_value = tf.convert_to_tensor([0.1187661])
final_value = tf.convert_to_tensor([0.8])
value_history = tf.convert_to_tensor([12., 0.06, 1.5])

In [104]:
deltas = reward_history + 0.99 * value_history[1:] - value_history[:-1]

In [105]:
advantages = []
gae = 0
for d in deltas[::-1]:
    gae = d + 0.99 * 0.95 * gae
    advantages.append(tf.expand_dims(gae, 0))
advantages.reverse()
print("advantages: ", advantages)

returns = []
ret = 0
for r in reward_history[::-1]:
    ret = r + 0.99 * ret
    returns.append(tf.expand_dims(ret, 0))
returns.reverse()
print("returns: ", returns)

advantages:  [<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-31.88639], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-10.575001], dtype=float32)>]
returns:  [<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-21.880001], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-12.], dtype=float32)>]


In [106]:
def compute_gae(next_value, rewards, values, gamma=0.99, tau=0.95):
#     values = values + [next_value]

    gae = 0
    returns = [] 
    for step in reversed(range(len(rewards))):
        delta = rewards[step] + gamma * values[step + 1]  - values[step]
        gae = delta + gamma * tau  * gae
        returns.insert(0, gae + values[step])
    print("GAE", returns)
    return returns

In [107]:
returns = compute_gae(final_value, reward_history, value_history)

GAE [<tf.Tensor: shape=(), dtype=float32, numpy=-19.88639>, <tf.Tensor: shape=(), dtype=float32, numpy=-10.515>]


In [108]:
returns - value_history[:2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-31.88639 , -10.575001], dtype=float32)>

In [32]:
aaa = tf.convert_to_tensor([[4]])
aaa

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[4]])>

In [34]:
tf.reshape(aaa, [np.shape(aaa)[0]])

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4])>

In [3]:
values = [tf.convert_to_tensor([0.4]), tf.convert_to_tensor([0.4])]
values

[<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.4], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.4], dtype=float32)>]

In [8]:
tf.reshape(values, [np.shape(values)[0]])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.4, 0.4], dtype=float32)>

In [35]:
ss = np.array([[1], [2], [3]])
ss

array([[1],
       [2],
       [3]])

In [41]:
a = np.zeros(shape=(10, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
idx = np.random.choice(5, 2)
idx

array([1, 0])

In [49]:
a[idx]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
gg = [0.2, 0.3]
gg.clear()

In [40]:
tf.math.minimum(0.3, 0.1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.1>

In [38]:
tf.reshape(ss, [np.shape(ss)[0]])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [23]:
tf.stack(tf.convert_to_tensor(ss), axis=1)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [14]:
next_state = tf.convert_to_tensor([[1], [2], [3]])
next_state

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]])>

In [18]:
tf.stack(next_state, axis=1)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [13]:
tf.reshape(next_state, [1, 3])

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [11]:
tf.expand_dims(next_state, 0)

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]])>

In [ ]:
states = [tf.convert_to_tensor([[1, 2, 3]]), tf.convert_to_tensor([[4, 5, 6]]), tf.convert_to_tensor([[7, 8, 9]])]

In [ ]:
b.shape[1]

In [ ]:
tf.reshape(a, [a.shape[1]])

In [ ]:
a = tf.convert_to_tensor([[1, 2, 3]])
b = tf.convert_to_tensor([[55.0]])
print(tf.reshape(a, [a.shape[1]]))
print(tf.squeeze(b))

In [ ]:
nate = [tf.convert_to_tensor([[1, 2, 3]]), tf.convert_to_tensor([[4, 5, 6]]), tf.convert_to_tensor([[7, 8, 9]])]
date = [tf.convert_to_tensor([1, 2, 3]), tf.convert_to_tensor([4, 5, 6]), tf.convert_to_tensor([7, 8, 9])]
# nate = [tf.convert_to_tensor([1]), tf.convert_to_tensor([4]), tf.convert_to_tensor([7])]
aa = tf.stack(nate, axis=1)
# tf.reshape(aa, [aa.shape[1]])


In [ ]:
tf.convert_to_tensor(np.vstack(nate))

In [ ]:
np.vstack(date)

In [ ]:
aa = [[0.11], [0.22], [0.33]]

In [ ]:
tf.cast(aa, tf.float32)

In [ ]:
bb = [[2.44]]

In [ ]:
tf.math.exp(-1.0338 - -1.0327488)

In [ ]:
np.shape(aa)[0]

In [ ]:
tf.convert_to_tensor(np.array(aa))

In [ ]:
aaa = tf.convert_to_tensor(aa)
tf.reshape(aa, [np.shape(aa)[0]])

In [ ]:
old = tf.convert_to_tensor([-1.29453373, -3.55276608, -1.06561875, -1.29182231])
new = tf.convert_to_tensor([-1.7613673, -2.1698098, -1.2520242, -2.007178])

tf.math.exp(new - old)